# ===========================
# PROFILE DE DESENVOLVIMENTO
# ===========================
spring.datasource.url=${DB_URL:jdbc:h2:mem:testdb}
spring.datasource.driverClassName=${DB_CLASSNAME:org.h2.Driver}
spring.datasource.username=${DB_USER:book}
spring.datasource.password=${DB_PASSWORD:123}
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=false

# Flyway - H2 usa as migrations adaptadas
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
