CREATE TABLE tb_user_book (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT,
    book_id BIGINT,

    status VARCHAR(50),
    current_page BIGINT DEFAULT 0,
    added_at TIMESTAMP,
    completed_at TIMESTAMP,

    CONSTRAINT fk_user_book_user FOREIGN KEY (user_id) REFERENCES tb_user(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_book_book FOREIGN KEY (book_id) REFERENCES tb_book(id) ON DELETE CASCADE,

    CONSTRAINT uk_user_book_user_id_book_id UNIQUE (user_id, book_id)
);
