ALTER TABLE tb_user
ADD COLUMN level INT NOT NULL DEFAULT 1,
ADD COLUMN experience INT NOT NULL DEFAULT 0,
ADD COLUMN pages_read INT NOT NULL DEFAULT 0;

ALTER TABLE tb_book ADD COLUMN description VARCHAR(255);
